run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - revive
    - gocyclo
    - bodyclose
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/dryaf/dnsfilter
  revive:
    rules:
      - name: exported
        severity: warning
      - name: package-comments
        severity: warning
      - name: error-naming
        severity: warning
      - name: error-strings
        severity: warning
      - name: error-return
        severity: warning
      - name: if-return
        severity: warning
      - name: var-naming
        severity: warning
      - name: var-declaration
        severity: warning
      - name: range
        severity: warning
      - name: receiver-naming
        severity: warning
      - name: indent-error-flow
        severity: warning
      - name: empty-block
        severity: warning

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0