---
- hosts: all
  gather_facts: no
  vars:
    # --- Project Variables ---
    service_name: "dns-filter"
    service_user: "dnsfilter"
    service_group: "dnsfilter"
    binary_name: "dns_filter"

    # --- Target Paths ---
    target_bin: "/usr/local/bin/{{ binary_name }}"
    target_bin_tmp: "/usr/local/bin/{{ binary_name }}.new"
    target_config: "/etc/dnsfilter.yml"

    # --- Local Paths ---
    local_binary_path: "service/{{ binary_name }}_linux"

    # --- Feature Flags ---
    wg_required: "no"
    # Set this to "yes" if you want the server to use ITSELF for DNS.
    # WARNING: Requires the Go code to strictly use `transport.DialContext` to avoid loops.
    use_local_dns: "yes"

  tasks:
    - name: Set install command
      set_fact:
        install_cmd: "{{ target_bin }} -service install {{ '-wg' if wg_required == 'yes' else '' }}"

    # --- Build Phase (Local) ---
    - name: Build the Linux binary
      delegate_to: localhost
      command:
        cmd: "go build -a -installsuffix cgo -o {{ binary_name }}_linux"
        chdir: service
      environment:
        GOOS: linux
        CGO_ENABLED: 0
        GOARCH: amd64

    # --- Preparation Phase (Remote) ---
    - name: Stop systemd-resolved service
      become: yes
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no
      ignore_errors: yes

    # --- Upload Phase (Atomic) ---
    - name: Upload the new binary to tmp location
      become: yes
      copy:
        src: "{{ local_binary_path }}"
        dest: "{{ target_bin_tmp }}"
        mode: "0755"
        owner: root
        group: root

    - name: Stop old service
      become: yes
      systemd:
        name: "{{ service_name }}"
        state: stopped
      ignore_errors: yes

    - name: Atomic move of new binary
      become: yes
      command:
        cmd: "mv {{ target_bin_tmp }} {{ target_bin }}"

    - name: Upload the new configuration
      become: yes
      copy:
        src: config.yml
        dest: "{{ target_config }}"
        mode: "0644"

    # --- Setup Phase ---
    - name: Create {{ service_group }} group
      become: yes
      group:
        name: "{{ service_group }}"
        state: present

    - name: Create {{ service_user }} user
      become: yes
      user:
        name: "{{ service_user }}"
        group: "{{ service_group }}"
        system: yes
        shell: /bin/false
        create_home: no

    - name: Set ownership of config
      become: yes
      file:
        path: "{{ target_config }}"
        owner: "{{ service_user }}"
        group: "{{ service_group }}"

    - name: Set capabilities on binary
      become: yes
      command:
        cmd: "setcap 'cap_net_bind_service=+ep' {{ target_bin }}"

    - name: Configure UFW for WireGuard
      become: yes
      ufw:
        rule: allow
        direction: in
        interface: wg0
        port: "53"
        proto: udp
      when: wg_required == 'yes'

    - name: Configure resolv.conf
      become: yes
      copy:
        content: "{{ 'nameserver 127.0.0.1\n' if use_local_dns == 'yes' else 'nameserver 1.1.1.2\n' }}"
        dest: /etc/resolv.conf
        mode: '0644'

    # --- Install & Start Phase ---
    - name: Install service (if not installed)
      become: yes
      command:
        cmd: "{{ install_cmd }}"
      register: install_result
      changed_when: "'already installed' not in install_result.stderr"
      failed_when: false # Ignore if already installed

    - name: Start and enable new service
      become: yes
      systemd:
        name: "{{ service_name }}"
        state: started
        enabled: yes
        daemon_reload: yes

    # --- Cleanup Phase (Local) ---
    - name: Remove local binary
      delegate_to: localhost
      file:
        path: "{{ local_binary_path }}"
        state: absent