---
- hosts: all
  gather_facts: yes
  vars:
    # --- Project Variables ---
    service_name: "dns-filter"
    service_user: "dnsfilter"
    service_group: "dnsfilter"
    binary_name: "dns_filter"

    # --- Target Paths ---
    target_bin: "/usr/local/bin/{{ binary_name }}"
    target_bin_tmp: "/usr/local/bin/{{ binary_name }}.new"
    target_config: "/etc/dnsfilter.yml"
    target_service_file: "/etc/systemd/system/{{ service_name }}.service"

    # --- Local Paths ---
    local_binary_path: "service/{{ binary_name }}_linux"

    # --- Feature Flags ---
    # "auto" will enable UFW rules if 'wg0' interface is found.
    wg_required: "auto"
    use_local_dns: "yes"

  tasks:
    # --- Connectivity Bootstrap ---
    - name: Temporarily set valid DNS for installation
      become: yes
      copy:
        content: "nameserver 1.1.1.1\n"
        dest: /etc/resolv.conf
        mode: '0644'
      tags: [bootstrap]

    # --- Dependency Checks ---
    - name: Ensure required system packages are installed
      become: yes
      package:
        name:
          - ufw
          - libcap2-bin # Required for setcap
        state: present
        update_cache: yes
      tags: [bootstrap]

    # --- Feature Detection ---
    - name: Detect WireGuard interface
      set_fact:
        wg_enabled: "{{ 'wg0' in ansible_facts['interfaces'] }}"
      when: wg_required == "auto"
      tags: [always]

    - name: Force WireGuard setting
      set_fact:
        wg_enabled: "{{ wg_required | bool }}"
      when: wg_required != "auto"
      tags: [always]

    - name: Set install command
      set_fact:
        install_cmd: "{{ target_bin }} -service install {{ '-wg' if wg_enabled else '' }}"
      tags: [always]

    # --- Build Phase (Local) ---
    - name: Build the Linux binary
      delegate_to: localhost
      command:
        cmd: "go build -a -installsuffix cgo -o {{ binary_name }}_linux"
        chdir: service
      environment:
        GOOS: linux
        CGO_ENABLED: 0
        GOARCH: amd64
      tags: [binary]

    # --- Preparation Phase (Remote) ---
    - name: Stop systemd-resolved service
      become: yes
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no
      ignore_errors: yes
      tags: [system]

    # --- Upload Phase (Atomic) ---
    - name: Upload the new binary to tmp location
      become: yes
      copy:
        src: "{{ local_binary_path }}"
        dest: "{{ target_bin_tmp }}"
        mode: "0755"
        owner: root
        group: root
      tags: [binary]

    # --- Graceful Stop ---
    - name: Check if service exists
      stat:
        path: "{{ target_service_file }}"
      register: service_file
      tags: [binary]

    - name: Stop old service
      become: yes
      systemd:
        name: "{{ service_name }}"
        state: stopped
      when: service_file.stat.exists
      tags: [binary]

    - name: Atomic move of new binary
      become: yes
      command:
        cmd: "mv {{ target_bin_tmp }} {{ target_bin }}"
      notify: Restart service
      tags: [binary]

    - name: Upload the new configuration
      become: yes
      copy:
        src: config.yml
        dest: "{{ target_config }}"
        mode: "0644"
      notify: Restart service
      tags: [config]

    # --- Setup Phase ---
    - name: Create {{ service_group }} group
      become: yes
      group:
        name: "{{ service_group }}"
        state: present
      tags: [setup]

    - name: Create {{ service_user }} user
      become: yes
      user:
        name: "{{ service_user }}"
        group: "{{ service_group }}"
        system: yes
        shell: /bin/false
        create_home: no
      tags: [setup]

    - name: Set ownership of config
      become: yes
      file:
        path: "{{ target_config }}"
        owner: "{{ service_user }}"
        group: "{{ service_group }}"
      tags: [setup]

    - name: Set capabilities on binary
      become: yes
      command:
        cmd: "setcap 'cap_net_bind_service=+ep' {{ target_bin }}"
      tags: [binary]

    - name: Configure UFW for WireGuard
      become: yes
      ufw:
        rule: allow
        direction: in
        interface: wg0
        port: "53"
        proto: udp
      when: wg_enabled
      tags: [firewall]

    - name: Configure resolv.conf
      become: yes
      copy:
        content: "{{ 'nameserver 127.0.0.1\n' if use_local_dns == 'yes' else 'nameserver 1.1.1.2\n' }}"
        dest: /etc/resolv.conf
        mode: '0644'
      tags: [dns]

    # --- Install & Start Phase ---
    - name: Install service (if not installed)
      become: yes
      command:
        cmd: "{{ install_cmd }}"
      register: install_result
      changed_when: "'already installed' not in install_result.stderr"
      failed_when: false
      tags: [binary]

    - name: Ensure service is enabled and running
      become: yes
      systemd:
        name: "{{ service_name }}"
        state: started
        enabled: yes
        daemon_reload: yes
      tags: [always]

    # --- Cleanup Phase (Local) ---
    - name: Remove local binary
      delegate_to: localhost
      file:
        path: "{{ local_binary_path }}"
        state: absent
      tags: [binary]

  handlers:
    - name: Restart service
      become: yes
      systemd:
        name: "{{ service_name }}"
        state: restarted
        daemon_reload: yes