---
- hosts: servers
  vars:
    target_bin: "/usr/local/bin/dns_filter"
    target_config: "/etc/dnsfilter.yml"
  vars_prompt:
    - name: "wg_required"
      prompt: "Is WireGuard requirement needed? (yes/no)"
      private: no
      default: "no"
  tasks:
    - name: Set install command
      set_fact:
        install_cmd: "{{ target_bin }} -service install {{ '-wg' if wg_required == 'yes' else '' }}"

    - name: Stop systemd-resolved service
      systemd:
        name: systemd-resolved
        state: stopped
      become: yes
      when: wg_required == 'no'

    - name: Disable systemd-resolved service
      systemd:
        name: systemd-resolved
        enabled: no
      become: yes

    - name: Build the Linux binary
      command:
        cmd: go build -a -installsuffix cgo -o dns_filter_linux
        chdir: service
      environment:
        GOOS: linux
        CGO_ENABLED: 0
        GOARCH: amd64
      delegate_to: localhost

    - name: Stop old service
      systemd:
        name: dns-filter
        state: stopped
      ignore_errors: yes

    - name: Uninstall old service
      command:
        cmd: "{{ target_bin }} -service uninstall"
      ignore_errors: yes

    - name: Remove the old binary
      file:
        path: "{{ target_bin }}"
        state: absent

    - name: Upload the new binary
      copy:
        src: service/dns_filter_linux
        dest: "{{ target_bin }}"
        mode: "0755"

    - name: Upload the new configuration
      copy:
        src: config.yml
        dest: "{{ target_config }}"
        mode: "0644"

    - name: Create dnsfilter group
      group:
        name: dnsfilter
        state: present

    - name: Create dnsfilter user
      user:
        name: dnsfilter
        group: dnsfilter
        system: yes
        shell: /bin/false

    - name: Set permissions on binary and config
      file:
        path: "{{ item }}"
        owner: dnsfilter
        group: dnsfilter
        mode: "0755"
      loop:
        - "{{ target_bin }}"
        - "{{ target_config }}"

    - name: Set capabilities on binary
      ansible.builtin.command:
        cmd: setcap 'cap_net_bind_service=+ep' "{{ target_bin }}"
      become: yes

    - name: Open port 53 on wg0 for DNS
      ansible.builtin.ufw:
        rule: allow
        direction: in
        interface: wg0
        port: "53"
        proto: udp
      become: yes
      when: wg_required == 'yes'

    - name: Install new service
      command:
        cmd: "{{ install_cmd }}"

    - name: Start new service
      systemd:
        name: dns-filter
        state: started

    - name: Check service status
      systemd:
        name: dns-filter
        state: started
        daemon_reload: yes
      register: service_status

    - debug:
        var: service_status

    - name: Remove local binary
      file:
        path: service/dns_filter_linux
        state: absent
      delegate_to: localhost
