---
- hosts: all
  gather_facts: no # Speed up connection if python is missing or just raw deployment
  vars:
    # --- Project Variables ---
    service_name: "dns-filter"
    service_user: "dnsfilter"
    service_group: "dnsfilter"
    binary_name: "dns_filter"

    # --- Target Paths ---
    target_bin: "/usr/local/bin/{{ binary_name }}"
    target_config: "/etc/dnsfilter.yml" # Renamed to standard location

    # --- Local Paths ---
    local_binary_path: "service/{{ binary_name }}_linux"

    # --- Feature Flags ---
    # Can be overridden via --extra-vars "wg_required=yes"
    wg_required: "no"

  tasks:
    - name: Set install command
      set_fact:
        install_cmd: "{{ target_bin }} -service install {{ '-wg' if wg_required == 'yes' else '' }}"

    # --- Build Phase (Local) ---
    - name: Build the Linux binary
      delegate_to: localhost
      command:
        cmd: "go build -a -installsuffix cgo -o {{ binary_name }}_linux"
        chdir: service
      environment:
        GOOS: linux
        CGO_ENABLED: 0
        GOARCH: amd64

    # --- Preparation Phase (Remote) ---
    - name: Stop systemd-resolved service
      become: yes
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Stop old service
      become: yes
      systemd:
        name: "{{ service_name }}"
        state: stopped
      ignore_errors: yes

    - name: Uninstall old service
      become: yes
      command:
        cmd: "{{ target_bin }} -service uninstall"
      ignore_errors: yes
      failed_when: false # Don't fail if binary doesn't exist

    - name: Remove the old binary
      become: yes
      file:
        path: "{{ target_bin }}"
        state: absent

    # --- Upload Phase ---
    - name: Upload the new binary
      become: yes
      copy:
        src: "{{ local_binary_path }}"
        dest: "{{ target_bin }}"
        mode: "0755"
        owner: root
        group: root

    - name: Upload the new configuration
      become: yes
      copy:
        src: config.yml
        dest: "{{ target_config }}"
        mode: "0644"

    # --- Setup Phase ---
    - name: Create {{ service_group }} group
      become: yes
      group:
        name: "{{ service_group }}"
        state: present

    - name: Create {{ service_user }} user
      become: yes
      user:
        name: "{{ service_user }}"
        group: "{{ service_group }}"
        system: yes
        shell: /bin/false
        create_home: no

    - name: Set ownership of config
      become: yes
      file:
        path: "{{ target_config }}"
        owner: "{{ service_user }}"
        group: "{{ service_group }}"

    - name: Set capabilities on binary
      become: yes
      command:
        cmd: "setcap 'cap_net_bind_service=+ep' {{ target_bin }}"

    - name: Configure UFW for WireGuard
      become: yes
      ufw:
        rule: allow
        direction: in
        interface: wg0
        port: "53"
        proto: udp
      when: wg_required == 'yes'

    - name: Configure resolv.conf
      become: yes
      copy:
        content: "nameserver 1.1.1.2\n"
        dest: /etc/resolv.conf
        mode: '0644'

    # --- Install & Start Phase ---
    - name: Install new service
      become: yes
      command:
        cmd: "{{ install_cmd }}"

    - name: Start and enable new service
      become: yes
      systemd:
        name: "{{ service_name }}"
        state: started
        enabled: yes
        daemon_reload: yes

    # --- Cleanup Phase (Local) ---
    - name: Remove local binary
      delegate_to: localhost
      file:
        path: "{{ local_binary_path }}"
        state: absent